#!/bin/bash

# Task 0: Extract Pokémon Data

#!/bin/bash

# Define the JSON file name
json_file="pokemon.json"

# Extract data using jq
pokemon_name=$(jq -r '.name' "$json_file")
pokemon_height_dm=$(jq -r '.height' "$json_file")  # Height in decimeters
pokemon_weight_hg=$(jq -r '.weight' "$json_file")  # Weight in hectograms
pokemon_types=$(jq -r '.types[].type.name' "$json_file" | paste -s -d ', ')


# Convert units using awk
pokemon_height_m=$(echo "$pokemon_height_dm" | awk '{printf "%.1fm", $1/10}')
pokemon_weight_kg=$(echo "$pokemon_weight_hg" | awk '{printf "%.1fkg", $1/10}')

# Format and print the output using printf
printf "%s is of type %s, weighs %s, and is %s tall.\n" "$pokemon_name" "$pokemon_types" "$pokemon_weight_kg" "$pokemon_height_m"